# Generated by Django 4.2.11 on 2024-06-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slugs',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
