# Generated by Django 4.2.11 on 2024-06-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='posts/media/images/default.png', upload_to='posts/media/images'),
        ),
    ]
