# Generated by Django 4.2.13 on 2024-06-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_rename_meals_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(default='meals/images/default.png', upload_to='meals/images'),
        ),
    ]
